### ISSUE TITLE
Embiggen Markdown headers

### ISSUE THREAD

**Issue by mcandre** [benjaminwhite/Benokai#2]
When viewing and editing markdown (.md, .markdown) files, it's helpful to render headers (`# Hello Header`) in large, bold font like:

# Hello Header

in order to find them in a long markdown document. Otherwise, they get lost in the text:

blah blah blah
Hello Header
blah blah blah

I asked [vim-markdown](https://github.com/plasticboy/vim-markdown/issues/74) about this, and they say this is an issue with the syntax color highlighter (in my case, Benokai, cause I love it and use it all the time).

**Comment by apennebaker-ni** [comment]
Apparently, the highlight group is htmlH1, htmlH2, htmlH3, ... htmlH6.

Could we also highlight these in green (`#67930F`), like [monokai-theme](https://github.com/oneKelvinSmith/monokai-emacs/blob/master/monokai-theme.el) for emacs does?
